apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: telegram-gateway
spec:
  minAvailable: {{ int .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: telegram-gateway