apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name | quote }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}