registry:
  image: paskalmaksim/telegram-gateway:1.0.3
  imagePullPolicy: IfNotPresent

replicas: 2

pdb:
  enabled: true
  minAvailable: 1

telegram:
- name: "telegram-gateway"
  cluster_name: "dev"
  token: "1072104160:AAH2sFpHELeH5oxMmd-tsVjgTuzoYO6hSLM"
  chat_id: "-479832859"
  urls:
    alertmanager: "https://test"
    prometheus: "https://test"

service:
  type: ClusterIP

resources:
  requests:
    memory: "20Mi"
  limits:
    memory: "20Mi"